# anything in <BRACKETS> should be modified
# with its actual value

version: "3.3"

services:
  db:
    platform: linux/x86_64 # for M1 macs
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "25060:3306"
    volumes:
      - <VOLUME NAME>:/var/lib/mysql

volumes:
  <VOLUME NAME>:
